repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    -   id: check-xml
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, develop, --branch, dev]   
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
    -   id: ruff
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint