# General Hooks ----------------------------------------------------------------------#
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    -   id: check-xml
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, develop, --branch, dev] 
    -   id: check-added-large-files
    -   id: check-ast
    -   id: detect-private-key
# Python  Hooks ----------------------------------------------------------------------#
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
    -   id: ruff
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.11.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
# C++ Hooks --------------------------------------------------------------------------#
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
    -   id: clang-format
-   repo: https://github.com/finsberg/clang-format-docs
    rev: v0.2.2
    hooks:
    -   id: clang-format-docs
# Git Hooks --------------------------------------------------------------------------#
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint