#!/usr/bin/env bash
set -euo pipefail

# Run from ansible/ so ansible.cfg and the inventory resolve.
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/ansible"
echo "==> Habitat setup"

# Prerequisites.
missing=()
command -v git >/dev/null || missing+=(git)
command -v ansible-playbook >/dev/null || missing+=(ansible)
command -v whiptail >/dev/null || missing+=(whiptail)
if (( ${#missing[@]} )); then
  sudo apt update
  sudo apt install -y "${missing[@]}"
fi

# Machine type — sets the inventory group.
case "$(uname -m)" in
  aarch64 | armv7l | armv6l) machine=raspberrypis ;;
  *) machine=laptops ;;
esac
read -rp "Detected machine type: $machine. Correct? [Y/n] " reply
if [[ ${reply,,} == n* ]]; then
  machine=$([[ $machine == laptops ]] && echo raspberrypis || echo laptops)
fi
echo "--> Provisioning as: $machine"

# Inventory. Ansible's become handshake is incompatible with sudo-rs (the Rust
# sudo that is default on Ubuntu 26.04+); point it at the classic sudo if found.
become_exe=""
if sudo --version 2>/dev/null | grep -qi sudo-rs && [ -x /usr/bin/sudo.ws ]; then
  echo "--> Detected sudo-rs; using /usr/bin/sudo.ws for privilege escalation"
  become_exe=" ansible_become_exe=/usr/bin/sudo.ws"
fi
cat > inventory <<EOF
[$machine]
localhost ansible_connection=local${become_exe}
EOF

# Components: use the committed group_vars profile, or pick per-machine.
read -rp "Use the default $machine component profile? [Y/n] " reply
if [[ ${reply,,} == n* ]]; then
  # Picker. Items are discovered from roles/ (minus the always-applied
  # base/uv/git/shell); boxes are pre-ticked from the currently resolved
  # selection (host_vars override if present, else the group_vars profile).
  current=" $(ansible-inventory --host localhost 2>/dev/null \
    | python3 -c 'import json,sys; print(" ".join(json.load(sys.stdin).get("components") or []))' \
    2>/dev/null || true) "

  items=()
  for dir in roles/*/; do
    role=$(basename "$dir")
    case $role in base | uv | git | shell) continue ;; esac
    [[ $current == *" $role "* ]] && state=ON || state=OFF
    items+=("$role" "" "$state")
  done

  list_h=$(( ${#items[@]} / 3 ))
  (( list_h > 12 )) && list_h=12
  selected=$(whiptail --title "Habitat — components" \
    --checklist "Select components to install (space toggles, Enter confirms):" \
    $(( list_h + 8 )) 60 "$list_h" \
    "${items[@]}" 3>&1 1>&2 2>&3) || { echo "Cancelled."; exit 1; }

  # whiptail emits selected tags space-separated and quoted; render a YAML list.
  components=$(echo "$selected" | tr -d '"' | xargs)
  components="[${components// /, }]"
  echo "--> Components: $components"

  # Per-machine selection — overrides the group_vars profile.
  mkdir -p host_vars
  cat > host_vars/localhost.yaml <<EOF
---
# Generated by setup.sh — per-machine component selection.
components: $components
EOF
else
  # Clear any stale per-machine override so the group_vars profile applies.
  echo "--> Using the default $machine profile"
  rm -f host_vars/localhost.yaml
fi

# Provision.
ansible-galaxy collection install -r requirements.yml
ansible-playbook site.yaml -K
