---
- name: Install fnm
  shell: curl -fsSL https://fnm.vercel.app/install | bash
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.local/share/fnm/fnm"
  become: false

- name: Install latest LTS Node.js via fnm
  shell: |
    eval "$("{{ ansible_env.HOME }}/.local/share/fnm/fnm" env)"
    fnm install --lts
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.local/share/fnm/node-versions"
  become: false
