---
extra_apt_packages: [terminator]

productivity: [obsidian, bitwarden]
creative: [obs]
entertainment: [spotify]


language_support: [python, cpp, javascript, rust]
ides: [vscode, zed, arduino]
tools: [uv, pixi, llm]
containerization: [docker, k8s]