---
- name: Check if Azure CLI is already installed
  shell: command -v az
  register: az_cli_check
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Install Azure CLI using official script
  shell: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  args:
    executable: /bin/bash
  when: az_cli_check.rc != 0

- name: Install Azure Storage Explorer using snap
  snap:
    name: storage-explorer
    state: present