---
- name: Download and add Spotify GPG key
  shell: curl -sS https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
  args:
    creates: /etc/apt/trusted.gpg.d/spotify.gpg

- name: Add Spotify repository
  apt_repository:
    repo: "deb https://repository.spotify.com stable non-free"
    filename: spotify
    state: present

- name: Update apt cache and install Spotify
  apt:
    name: spotify-client
    state: present
    update_cache: yes