---
- name: Check if VS Code exists
  stat:
    path: /usr/bin/code
  register: code_exists

- name: Pre-seed VS Code to register the Microsoft apt repo
  debconf:
    name: code
    question: code/add-microsoft-repo
    value: "true"
    vtype: boolean
  become: yes
  when: not code_exists.stat.exists

- name: Download and install VS Code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
    state: present
  become: yes
  when: not code_exists.stat.exists
