---
- name: Install base packages
  apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes
  become: yes
  when:
    - base_packages is defined
    - base_packages | length > 0

- name: Install extra apt packages
  apt:
    name: "{{ extra_apt_packages }}"
    state: present
    update_cache: yes
  become: yes
  when:
    - extra_apt_packages is defined
    - extra_apt_packages | length > 0

- name: Install OpenSSH server
  apt:
    name: openssh-server
    state: present
  become: yes
  when: install_ssh_server | default(false)

- name: Enable and start SSH service
  service:
    name: ssh
    enabled: yes
    state: started
  become: yes
  when: install_ssh_server | default(false)

- name: Install uv
  include_tasks: tools/uv.yaml
