---
- name: Install Git tools
  include_tasks: tools/git.yaml

- name: Install shell tools
  include_tasks: tools/shell.yaml

- name: Install language support
  include_tasks: "languages/{{ item }}.yaml"
  loop: "{{ language_support }}"
  when:
    - language_support is defined
    - language_support | length > 0

- name: Install IDEs
  include_tasks: "apps/{{ item }}.yaml"
  loop: "{{ ides }}"
  when:
    - ides is defined
    - ides | length > 0

- name: Install tools
  include_tasks: "tools/{{ item }}.yaml"
  loop: "{{ tools }}"
  when:
    - tools is defined
    - tools | length > 0
