---
- name: Install Git Tooling via UV
  include_tasks: utils/uv-tool-install.yaml
  vars:
    tools:
      - name: pre-commit
        with: [pre-commit-uv]

# TODO Github CLI
# TODO Github SSH Key
# TODO Git name + Email

# TODO: Other SSH Key

